version: "3.8"

services:
  neo4j:
    image: neo4j:latest
    container_name: 'neo4j'
    env_file:
      - .env
    environment:
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4JLABS_PLUGINS=["apoc"]
      - NEO4J_dbms_security_procedures_whitelist=apoc.*
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
    volumes:
      - neo4j_data:/var/lib/neo4j/data/
      - neo4j_data:/var/lib/neo4j/conf/
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
    command: neo4j

  api:
    container_name: api2
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - neo4j

volumes:
  neo4j_data:
