version: "3.8"

services:
  neo4j:
    image: neo4j:latest
    container_name: 'neo4j'
    env_file:
      - .env
    volumes:
      - neo4j_data:/var/lib/neo4j/data/
      - neo4j_data:/var/lib/neo4j/conf/
    ports:
      - 7474:7474
      - 7687:7687
    restart: on-failure
#    networks:
#        - neo4j_python_net
    command: neo4j

  api:
    container_name: api2
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - neo4j
#    networks:
#      - neo4j_python_net

#networks:
#  neo4j_python_net:
#    driver: bridge

volumes:
  neo4j_data:
